services:
  flask-app:
    image: irbis3/flask-backend:latest
    ports:
      - "5000:5000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306
      FLASK_ENV: development
    command: python app.py

volumes:
  mysql_data:
